### ISSUE TITLE
Could Not Type Load LegacyBar.Library.BarActions.LegacyBarMenuItem

### ISSUE THREAD

**Issue by jmawebtech** [Cheesebaron/LegacyBar#42]
Hi,

I am trying to add buttons and menu items. Can you send me documentation, please?

I tried this code, but am I missing an assembly? I got the error in the subject.

LegacyBar = FindViewById<LegacyBar.Library.Bar.LegacyBar>(Resource.Id.actionbar);
            LegacyBar.SetHomeLogo(Resource.Drawable.Icon);
            MenuId = Resource.Menu.mainmenu;

```
        var searchMenuItemAction = new MenuItemLegacyBarAction(
            this, Resource.Id.menu_search, LegacyBar.LightIcons ? Resource.Drawable.ic_action_share : Resource.Drawable.ic_action_share_dark,
            Resource.String.menu_string_search)
        {
            ActionType = ActionType.IfRoom
        };
        LegacyBar.AddAction(searchMenuItemAction);
```

**Comment by Cheesebaron** [comment]
What are your minimum and target API levels?

There is only the documentation found in the Wiki.

**Comment by jmawebtech** [comment]
Hi,

My target is 4.2 and my min version is 1.6. It works fine in the sample project, however, it fails with mine. I noticed that CurrentActivity does not exist:

LegacyBar.CurrentActivity = this;

I added some docs, mostly on set-up, on my blog:

http://www.jmawebtechnologies.com/company-blog/may-2013/installing-and-customizing-legacy-bar-mono-for-and

I would be happy to document features, so let me how to proceed.

**Comment by jamesmontemagno** [comment]
All of the documentation is on the wiki: https://github.com/Cheesebaron/LegacyBar/wiki

We removed "CurrentActivity" as a requirement when settings up the legacybar, please ensure tha tyou have the latest code.

I separated out your blog into a separate section.

**Comment by jamesmontemagno** [comment]
Additionally your legacybar xaml should be as simple as
`<legacybar.library.bar.LegacyBar
      android:id="@+id/actionbar"
      style="@style/actionbar"
      ab:theme="holo_gray"/>
`

See this: https://github.com/Cheesebaron/LegacyBar/wiki/Customizing-the-ActionBar

**Comment by jmawebtech** [comment]
Thanks, I made the changes. When you get a chance, can you look at my project? It is located at www.jmawebtechnologies.com/glass.android.zip

**Comment by Cheesebaron** [comment]
It is not really recommended to have `Android` in your namespace it clashes with the `Android` namespace Xamarin provides.

Also don't put the LegacyBar into a ScrollView otherwise it will disappear when you start scrolling your View. Also your manifest says Minimum target is 4, that won't work as we are using `match_parent` in our layout for the LegacyBar, which means minimum API level is 7, this will be corrected in the documentation soon.

**Comment by jmawebtech** [comment]
Thanks for the feedback. I have made the namespace and layout changes. I went to project > options > android build and set the min target to 7, however, the error persists. 

Go to Base > Custom Activity > DoMenu and uncomment the search code. 

My new code is here: www.jmawebtechnologies.com/archive.zip

**Comment by Cheesebaron** [comment]
Please make a small reproducible sample I can't work with this too many errors to correct. I don't have your Core project which is used everywhere.

**Comment by jmawebtech** [comment]
Hi,

Go to www.jmawebtechnologies.com/glass-master.zip

**Comment by Cheesebaron** [comment]
I don't seem to get the error. I can launch the App just fine. Changed the API level 7 without any problems.

![device-2013-05-02-204110](https://f.cloud.github.com/assets/249719/455725/128212fe-b359-11e2-9780-02c23511e3db.png)

**Comment by jmawebtech** [comment]
Hi,

In Glass.UI.AN, go to the base folder and go to CustomActivity.

The code looks like this:

//          var searchMenuItemAction = new MenuItemLegacyBarAction(
//              this, Resource.Id.menu_search, LegacyBar.LightIcons ? Resource.Drawable.ic_action_share : Resource.Drawable.ic_action_share_dark,
//              Resource.String.menu_string_search)
//          {
//              ActionType = ActionType.Always
//          };
//          LegacyBar.AddAction(searchMenuItemAction);

**Comment by Cheesebaron** [comment]
Still works here, removed the comments, cleaned, recompiled and deployed, not getting your error.

![device-2013-05-02-204110](https://f.cloud.github.com/assets/249719/455836/b0bcf83c-b35c-11e2-9a13-093535dc9ab6.png)

**Comment by Cheesebaron** [comment]
I want to help, but I for some reason can't reproduce your problem here. In the future please do not dump all your code at me and simply make a small reproducible sample, makes things so much easier and faster to debug, rather than going through baklava cake layers of code to get to the core problem. Please do re-open if you still experience the bug.
